name: Build, Push to Docker Hub, and Deploy

on:
  push:
    branches: ["main"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          COMMIT_SHA=$(git rev-parse --short HEAD)
          docker build \
            -t cloudwpa22/app-gastos_mensais:latest \
            -t cloudwpa22/app-gastos_mensais:git-$COMMIT_SHA .
          docker push cloudwpa22/app-gastos_mensais --all-tags

  deploy-to-vm:
    needs: build-and-push
    runs-on: [self-hosted, "dockerdebian12"]  # 🔥 Usando o nome do seu runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Pull and Update Containers
        run: |
          docker pull cloudwpa22/app-gastos_mensais:latest
          docker-compose -f /opt/app-gastos_mensais/docker-compose.yml down
          docker-compose -f /opt/app-gastos_mensais/docker-compose.yml up -d

      - name: Cleanup  # 🔥 Passo de limpeza adicionado
        run: docker system prune -f --all